version: "3.9"
services:
  test:
    image: spark-test
    build:
      context: .
      dockerfile: Dockerfile   
    environment:
      - PYTHONPATH=./src
    volumes:
      - .:/app
    command: python3 -m pytest